/**
 * vectorSearch.ts
 * ─────────────────────────────────────────────────────────
 * Loads the pre-built vector store (generated by npm run ingest)
 * and performs cosine-similarity search at query time using
 * a fresh Gemini query embedding.
 *
 * Falls back to empty results (→ keyword search takes over)
 * if the vector store has not been generated yet.
 */

import { existsSync, readFileSync } from "fs";
import { join } from "path";
import { GoogleGenerativeAI } from "@google/generative-ai";

// ── Types ─────────────────────────────────────────────────────────────────────
interface StoredChunk {
  id: string;
  source: string;
  fileTitle: string;
  heading: string;
  content: string;
  category: string;
  embedding: number[];
}

interface VectorStore {
  version: number;
  generatedAt: string;
  model: string;
  dimensions: number;
  chunkCount: number;
  chunks: StoredChunk[];
}

// Shape compatible with what route.ts already expects from searchLegalDocs
export interface VectorSearchResult {
  title: string;
  section?: string;
  category: string;
  content: string;
  score: number;
}

// ── Lazy-load the vector store (once per process) ─────────────────────────────
let _store: VectorStore | null = null;
let _storeLoaded = false;

function loadStore(): VectorStore | null {
  if (_storeLoaded) return _store;
  _storeLoaded = true;

  const storePath = join(process.cwd(), "src", "lib", "vector-store.json");
  if (!existsSync(storePath)) {
    console.warn("[vectorSearch] vector-store.json not found. Run: npm run ingest");
    _store = null;
    return null;
  }

  try {
    const raw = readFileSync(storePath, "utf8");
    _store = JSON.parse(raw) as VectorStore;
    console.log(
      `[vectorSearch] Loaded ${_store.chunkCount} chunks (${_store.dimensions}d, generated ${_store.generatedAt.slice(0, 10)})`
    );
    return _store;
  } catch (err) {
    console.error("[vectorSearch] Failed to parse vector-store.json:", err);
    _store = null;
    return null;
  }
}

// ── Cosine similarity ─────────────────────────────────────────────────────────
function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0, magA = 0, magB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    magA += a[i] * a[i];
    magB += b[i] * b[i];
  }
  const denom = Math.sqrt(magA) * Math.sqrt(magB);
  return denom === 0 ? 0 : dot / denom;
}

// ── Gemini embedding client ───────────────────────────────────────────────────
let _embeddingModel: ReturnType<InstanceType<typeof GoogleGenerativeAI>["getGenerativeModel"]> | null = null;

function getEmbeddingModel() {
  if (!_embeddingModel) {
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
    _embeddingModel = genAI.getGenerativeModel({ model: "text-embedding-004" });
  }
  return _embeddingModel;
}

// ── Main search function ──────────────────────────────────────────────────────
/**
 * Searches the vector store for chunks relevant to `query`.
 * Returns up to `limit` results sorted by cosine similarity descending.
 * Returns [] if the vector store does not exist or embedding fails.
 */
export async function vectorSearch(
  query: string,
  limit = 3
): Promise<VectorSearchResult[]> {
  const store = loadStore();
  if (!store || store.chunks.length === 0) return [];

  try {
    const model = getEmbeddingModel();
    const result = await model.embedContent(query);
    const queryEmbedding = result.embedding.values;

    const scored = store.chunks.map((chunk) => ({
      chunk,
      score: cosineSimilarity(queryEmbedding, chunk.embedding),
    }));

    return scored
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .filter((s) => s.score > 0.3) // minimum relevance threshold
      .map((s) => ({
        title: `${s.chunk.heading}`,
        section: s.chunk.heading,
        category: s.chunk.category,
        content: s.chunk.content,
        score: s.score,
      }));
  } catch (err) {
    console.error("[vectorSearch] Query embedding failed, falling back to keyword search:", err);
    return [];
  }
}

// ── Store metadata (for logging/debugging) ────────────────────────────────────
export function getStoreInfo(): { exists: boolean; chunkCount: number; generatedAt: string } {
  const store = loadStore();
  if (!store) return { exists: false, chunkCount: 0, generatedAt: "" };
  return { exists: true, chunkCount: store.chunkCount, generatedAt: store.generatedAt };
}
